# Generated by Django 2.0.5 on 2018-05-09 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('instituicao', 'Instituição'), ('pessoal', 'Pessoal')], default='pessoal', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('tipopessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='appAgenda.TipoPessoa')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('user_name', models.CharField(max_length=50, verbose_name='Nome do perfil')),
                ('senha', models.CharField(max_length=20, verbose_name='Senha')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
            ],
            bases=('appAgenda.tipopessoa',),
        ),
    ]
